# Generated by Django 3.2.7 on 2021-09-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='url_username',
            field=models.CharField(default='samsuchin', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
