# Generated by Django 3.2.7 on 2022-01-04 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20211207_0422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='position',
        ),
        migrations.AddField(
            model_name='user',
            name='positions',
            field=models.CharField(blank=True, help_text='Comma seperated positions', max_length=150, null=True),
        ),
    ]
