# Generated by Django 3.2.7 on 2022-01-04 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20220104_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='year_joined',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
