# Generated by Django 3.2.7 on 2021-09-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='url_username',
            field=models.CharField(help_text='harvardlampoon/@<YOUR_URL_USERNAME>/', max_length=200, unique=True),
        ),
    ]
