# Generated by Django 3.2.7 on 2021-11-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_url_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='use_real_name',
            field=models.BooleanField(default=False),
        ),
    ]
