# Generated by Django 3.2.7 on 2021-09-20 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='advertiser',
        ),
        migrations.AddField(
            model_name='ad',
            name='company_name',
            field=models.CharField(default='American Eagle', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Advertiser',
        ),
    ]
