# Generated by Django 3.2.7 on 2021-09-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_auto_20210920_0054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='size_type',
            new_name='ad_type',
        ),
        migrations.AddField(
            model_name='ad',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ad',
            name='image',
            field=models.ImageField(null=True, upload_to='ads/'),
        ),
    ]
