# Generated by Django 3.2.7 on 2021-09-22 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_alter_ad_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='company_name',
        ),
    ]
