# Generated by Django 3.2.7 on 2022-01-02 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='views',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
