# Generated by Django 3.2.7 on 2021-09-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='title',
            field=models.CharField(default='Test', max_length=200),
            preserve_default=False,
        ),
    ]
