# Generated by Django 3.2.7 on 2021-09-10 02:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0002_work_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='owner',
            new_name='writer',
        ),
        migrations.AddField(
            model_name='work',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='work',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='voice_file',
            field=models.FileField(blank=True, null=True, upload_to='voices/'),
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('special_link', models.URLField(blank=True, null=True)),
                ('works', models.ManyToManyField(related_name='magazines', to='read.Work')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year_published', models.CharField(max_length=4)),
                ('seller_link', models.URLField()),
                ('active', models.BooleanField(default=True)),
                ('description', tinymce.models.HTMLField()),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='read.artwork')),
            ],
        ),
    ]
