# Generated by Django 3.2.7 on 2021-09-10 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0003_auto_20210910_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='title',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='classic',
            field=models.BooleanField(default=False),
        ),
    ]
