# Generated by Django 3.2.7 on 2021-09-10 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0004_auto_20210910_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='title',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
