# Generated by Django 3.2.7 on 2021-09-10 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0005_magazine_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
