# Generated by Django 3.2.7 on 2021-09-12 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0006_alter_work_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='custom_display_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
