# Generated by Django 3.2.7 on 2021-09-13 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0007_work_custom_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='work',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
