# Generated by Django 3.2.7 on 2021-09-14 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0008_auto_20210913_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='smile_score',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
