# Generated by Django 3.2.7 on 2021-09-14 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0009_work_smile_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='smile_score',
            new_name='laugh_score',
        ),
    ]
