# Generated by Django 3.2.7 on 2021-09-14 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0010_rename_smile_score_work_laugh_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='art_work',
        ),
        migrations.AddField(
            model_name='work',
            name='art_works',
            field=models.ManyToManyField(related_name='works', to='read.ArtWork'),
        ),
    ]
