# Generated by Django 3.2.7 on 2021-09-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0011_auto_20210914_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
