# Generated by Django 3.2.7 on 2021-09-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0012_artwork_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='custom_display_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
