# Generated by Django 3.2.7 on 2021-09-14 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0013_artwork_custom_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='original_work',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='work',
            name='original_work',
            field=models.BooleanField(default=True),
        ),
    ]
