# Generated by Django 3.2.7 on 2021-09-15 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0014_auto_20210914_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='read.artwork'),
        ),
    ]
