# Generated by Django 3.2.7 on 2021-09-16 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('read', '0015_magazine_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='art_editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='art_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='magazine',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='magazine',
            name='issue_editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
