# Generated by Django 3.2.7 on 2021-09-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0016_auto_20210916_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
