# Generated by Django 3.2.7 on 2021-09-20 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0018_auto_20210918_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
