# Generated by Django 3.2.7 on 2021-09-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0019_alter_work_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='created_at',
            field=models.DateTimeField(blank=True, help_text='Testing 123', null=True),
        ),
    ]
