# Generated by Django 3.2.7 on 2021-09-20 06:10

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0020_alter_work_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='created_at',
            field=models.DateTimeField(blank=True, help_text='Written as YYYY-MM-DD HH:MM:SS', null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='custom_display_name',
            field=models.CharField(blank=True, help_text='Leave blank if you want your name to show up', max_length=200, null=True),
        ),
    ]
