# Generated by Django 3.2.7 on 2021-09-20 06:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0021_auto_20210920_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Written as YYYY-MM-DD HH:MM:SS'),
            preserve_default=False,
        ),
    ]
