# Generated by Django 3.2.7 on 2021-09-20 06:22

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0023_alter_work_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='content',
            field=tinymce.models.HTMLField(default='test'),
            preserve_default=False,
        ),
    ]
