# Generated by Django 3.2.7 on 2021-09-20 06:23

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0024_alter_work_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
