# Generated by Django 3.2.7 on 2021-09-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0025_alter_work_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
