# Generated by Django 3.2.7 on 2021-09-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0026_alter_work_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='custom_display_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
