# Generated by Django 3.2.7 on 2021-09-30 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0031_book_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateField(blank=True, help_text='Written as YYYY-MM-DD', null=True),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='created_at',
            field=models.DateField(blank=True, help_text='Written as YYYY-MM-DD', null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='created_at',
            field=models.DateField(blank=True, help_text='Written as YYYY-MM-DD', null=True),
        ),
    ]
