# Generated by Django 3.2.7 on 2021-11-26 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0032_auto_20210930_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='art_works',
        ),
        migrations.AddField(
            model_name='work',
            name='art_work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='works', to='read.artwork'),
        ),
    ]
