# Generated by Django 3.2.7 on 2021-11-26 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0033_auto_20211126_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazine',
            name='works',
        ),
        migrations.AddField(
            model_name='work',
            name='magazine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='read.magazine'),
        ),
    ]
